Added Windows ZIP fix for #110

diff --git a/Assets/provisioners/demo-tasks/0.1.20/scripts/ansible/roles/domino_vagrant_rest_api/templates/run_dxl_importer.sh.j2 b/Assets/provisioners/demo-tasks/0.1.20/scripts/ansible/roles/domino_vagrant_rest_api/templates/run_dxl_importer.sh.j2
--- a/Assets/provisioners/demo-tasks/0.1.20/scripts/ansible/roles/domino_vagrant_rest_api/templates/run_dxl_importer.sh.j2
+++ b/Assets/provisioners/demo-tasks/0.1.20/scripts/ansible/roles/domino_vagrant_rest_api/templates/run_dxl_importer.sh.j2
@@ -21,7 +21,12 @@ mkdir -p $TMP_DIR
 
 # unzip and setup project
 cd $TMP_DIR
-unzip $ZIP_FILE
+unzip $ZIP_FILE || EXIT_CODE=$?
+if [ "$EXIT_CODE" -gt 1]; then
+    echo "unzip failed with exit code $EXIT_CODE";
+    exit $EXIT_CODE;
+fi
+sudo chown -R vagrant.vagrant .
 ln -s {{ service_home_dir }}/notes.ini
 
 # Update Domino path
